### ISSUE TITLE
UpdateCacheHandler is not called after Pagination

### ISSUE THREAD

**Issue by agent3bood** [gql-dart/ferry#106]
Hi

I have a request to fetch a list of items, and a loadMore function for pagination, sane as in the example https://ferrygraphql.com/docs/pagination

The initial request will call the UpdateCacheHandler, but any loadMore calls will not call it!
Is this expected behavior? 

extra information about the app ligic:
What I am doing with UpdateCacheHandler?
I want to write each item from the results of `getItems(limit, offset)` to cache, so 
  1. individual item fetch `getItem(id)` will be from cache 
  2. when I update any property of the item from one page I rewrite the item fragment and it will update both requests.

**Comment by smkhalsa** [comment]
To handle pagination, you need to specify an `updateResult` callback, not an UpdateCacheHandler. Take another look at the [docs](https://ferrygraphql.com/docs/pagination/#pagination).

Also, a few notes:
1. Results will only be updated if the request has the same `requestId`. If no `requestId` is specified, a unique ID will be generated automatically. If you're using Flutter, make sure you either instantiate the request outside of the `build()` method (so that it doesn't get instantiated on every build with a new ID) or explicitly provide an ID. 
2. Ferry doesn't have any way of knowing that a `getItem(id)` query should return one of the results previously returned by 
a `getItems()` query. You can specify a `FieldPolicy.read()` function on the `getItems` field of your `Query` Typepolicy to allow for this behavior, but working with TypePolicies and FieldPolicies is not yet well documented. (although this functionality closely mirrors Apollo's use of TypePolicies, so their docs on this topic could provide you some guidance).

**Comment by agent3bood** [comment]
Thanks @smkhalsa for explaining this to me, I am aware of  `updateResult` function and I am using it.
Maybe I did not explain the issue clearly, here are steps I am doing
1. `getItems(limit = 10, offset = 0)` this function will keep listening to the result items
2. I do update an item at index between 0 and 10 using a mutation request and I do update the item fragment using `writeFragment()`
3. The listener from step 1 will get a new event with the updated fragment from cache and then from server.
4. I do the pagination process as in the docs, rebuild the request and add it to the requestController `updateResult` is called to add the new items to the previous, and then the listener from step 1 called with the new list.
5. If I update an item indexed 10 to 20 (using `writeFragment`) the listener from step 1 is called; but if I update an item indexed 0 to 10 the listener from step ` is NOT called which is an issue form me.
I want to know the behavior is step 5 is expected or is it a bug?

Thanks again for the answer and this great library

**Comment by smkhalsa** [comment]
Are you using the latest version of ferry (0.8.0)?

**Comment by agent3bood** [comment]
No, I am using ferry: ^0.7.6 I could not upgrade because of the rxdart version.
Is it possible to make the rxdart version as a range 
something like rxdart: ">=2.0.0 <3.0.0"

**Comment by smkhalsa** [comment]
Ok, this issue should be fixed in the latest version.

You can set a dependency_override on rxdart for the beta version.

**Comment by agent3bood** [comment]
Thanks, it is working fine after the upgrade.
