### ISSUE TITLE
[normalize] Mutations with the same variables overwrite previous results

### ISSUE THREAD

**Issue by micimize** [gql-dart/ferry#122]
If a mutation like `createOrder($placeId: ID!)` returns different orders every time, the new one will overwrite the old in the cache. This can lead to incorrect mutations results for reactive clients like `graphql/client.dart` and probably `ferry` as well: https://github.com/zino-app/graphql-flutter/issues/774#issuecomment-732216733.

I'm not sure what the best solution is, or if it is even an issue for `normalize` to solve itself.

**Comment by smkhalsa** [comment]
Let me know if you think of a way around this, but it seems like the existing behavior is the expected behavior, even if it results in incorrect mutation results in some cases.

This should probably be addressed by simply not reading mutation results from the cache by default. In `ferry`, mutations use `FetchPolicy.NetworkOnly` by default, and the FetchPolicy is not coupled to reactivity.

If a user needs to use cached mutation results, they could use unique variables or define custom `FieldPolicy` read / merge functions to alter the default behavior.

**Comment by micimize** [comment]
Ok – yeah that's kind of what I was leaning towards also. I think the real problem is the use of `cacheAndNetwork` due to the entanglement of `ObservableQuery` in `graphql/client.dart`
