### ISSUE TITLE
ferry_generator creates new ListBuilder() for optional List fields

### ISSUE THREAD

**Issue by graphicbeacon** [gql-dart/ferry#131]
I first want to thank you for the great work you are doing with this project. I made a [tutorial](https://youtu.be/e_5m-LmWaro) with this package and in the middle of my second one and would be great to get some help with the below issue.

So given this input structure:

```graphql
input Int_comparison_exp {
   _eq: Int
   _in: [Int!]
}
```
The **ferry_generator** package generates the following lines for the `_in` field:

```dart
ListBuilder<int> get G_in => _$this._G_in ??= new ListBuilder<int>();
```

The issue here is that this affects the query variables sent to the server in the payload:

```js
{ _eq: 18, _in: [] }
```

And that consequently affects the results returned from the server, which in my case is **an empty list**. 

Ideally the `_in` field should not be given a ListBuilder object since it is optional. In other words the generator should assign a new ListBuilder() object **only when the field is required**:

```graphql
_in: [Int!]!
```

My current workaround is disabling the `_in` field from my schema, but would be great to get your feedback on this. Thanks again.

**Comment by smkhalsa** [comment]
First of all, thanks so much for the tutorials! I look forward to checking out the second one. We can add some links to them in the repo or doc site as a supplemental resource if you'd like.

With respect to the above issue, I believe this is caused by [this](https://github.com/google/built_value.dart/issues/809) in the underlying `built_value` package. 

As noted in that issue, you should be able to set the nested builder to `null`, but reading it will automatically reset it to an empty collection.

**Comment by graphicbeacon** [comment]
@smkhalsa Thanks so much for your prompt response. I'll try your suggestion and confirm. 

I'm planning the second tutorial for Christmas. Do add the first tutorial link to your docs so others can get the ferry ;)

**Comment by graphicbeacon** [comment]
@smkhalsa Looks like the reset behaviour makes it impossible to achieve what I'm looking for. For now I'm able to disable those fields on the schema. I'll go ahead and close this issue since it's not directly caused by ferry. Thanks again for your help.
