### ISSUE TITLE
ferry_test_graphql remove dependency ferry_exec, but it is just dev_dependencies

### ISSUE THREAD

**Issue by huang12zheng** [gql-dart/ferry#152]
it is from #130 
https://github.com/gql-dart/ferry/pull/130/commits/029a3c4f7976c405d59dd4457f056884d75cee4f

Can you tell me more info about what you found?

**Comment by smkhalsa** [comment]
I'm not sure what you're asking here.

**Comment by huang12zheng** [comment]
I think `ferry_exec` should be added.
But I noticed you remove it.
It's confusing to me.

I don't understand what your scene was like, although my IDE will report an error as follow


<img width="1680" alt="截屏2021-02-11 下午6 30 07" src="https://user-images.githubusercontent.com/28038074/107625604-827ca380-6c97-11eb-9286-bca53508d1c6.png">
<img width="1680" alt="截屏2021-02-11 下午6 29 54" src="https://user-images.githubusercontent.com/28038074/107625615-87415780-6c97-11eb-9b7d-b3d076b1ee46.png">

**Comment by smkhalsa** [comment]
Ah. I understand.

Yes, I purposefully removed the `ferry_exec` dependency because I use [`multipack`](https://github.com/gql-dart/multipack) to help manage the monorepo, and multipack [can't handle circular dependencies](https://github.com/gql-dart/multipack/issues/2).

The actual published version (on pub.dev) of `ferry_gest_graphql` includes the `ferry_exec` dependency though.

**Comment by smkhalsa** [comment]
closing since this isn't an issue.

I suggest using the discord channel for general discussion about the library.
