### ISSUE TITLE
Use generated data classes for optimistic response

### ISSUE THREAD

**Issue by awaik** [gql-dart/ferry#17]
Hello, as you recommended, I made an optimisticResponse, and it works just fine. I got data from this response and can use it before I get updates from API.

This question is about best practices. 

In the app, we made a mutation and passes there the 'resultObjectFromApp'. For the optimisticResponse we should create a 'mapFromApp' with structure

```
{QueryName: 
  {__typename: TypeName,  
  height: xx, 
  weight: xx,
  birthday: xx}
}
```

where all the data except `{**QueryName**: {__typename: **TypeName**,  ` duplicate `resultObjectFromApp` data.

So, the question is - are there any ways to create this map outside widgets or, maybe, it is possible to implement the automatic creation of this map?

```
final mutation = SomeMutation(
  buildVars: (b) => b..input = resultObjectFromApp,
  updateCacheHandlerKey:
      IdCacheHandlers.someMutation,
  optimisticResponse: mapFromApp,
).copyWith(
  context: Context.fromList(
    [
      HttpLinkHeaders(
        headers: idToken,
      ),
    ],
  ),
);
client
    .responseStream(mutation)
    .firstWhere((response) => response.optimistic)
    .then((response) {
});
```

**Comment by smkhalsa** [comment]
> So, the question is - are there any ways to create this map outside widgets or, maybe, it is possible to implement the automatic creation of this map?

Yes, it would definitely be more user-friendly to use the generated query data objects for optimistic responses rather than having to recreate the object data manually.

Ferry simply [parses](https://github.com/gql-dart/ferry/blob/master/lib/src/client/client.dart#L132) the optimistic response JSON that the user passes into the generated query data object, so it should be pretty straightforward to simply pass the generated object directly.

Ferry depends on the `gql_build` / `gql_code_builder` packages to generate the Dart GraphQL types. The [`data_builder`](https://github.com/gql-dart/gql/blob/master/gql_build/lib/src/data_builder.dart) is responsible for generating the Dart type for GraphQL query responses, which for a query like this...

```graphql
query AlbumDetailsQuery($id: ID!) {
  Album(id: $id) {
    id
    name
    imageUrl
  }
}
```
 ...will generate these types:

```dart
class $AlbumDetailsQuery {
  const $AlbumDetailsQuery(this.data);

  final Map<String, dynamic> data;

  List<$AlbumDetailsQuery$Album> get Album => data['Album'] == null
      ? null
      : (data['Album'] as List)
          .map((dynamic e) =>
              $AlbumDetailsQuery$Album((e as Map<String, dynamic>)))
          .toList();
}

class $AlbumDetailsQuery$Album {
  const $AlbumDetailsQuery$Album(this.data);

  final Map<String, dynamic> data;

  String get id => (data['id'] as String);
  String get name => (data['name'] as String);
  String get imageUrl => (data['imageUrl'] as String);
}
```

As you can see, these generated types currently [only include getters](https://github.com/gql-dart/gql/blob/master/gql_code_builder/lib/src/operation/data.dart#L152).

Ideally, we'd update `data_builder` to move the current default constructor to a named `fromJSON` constructor and add a builder function as the default constructor.

@klavs, any thoughts on making the above change? It will be a breaking change, but it seems the most intuitive to me. I can take a pass at it if you agree.

**Comment by klavs** [comment]
Yes, I had not considered this.

Before making the breaking change, could you sketch the intended result and usage of the generated code? I'm worried about interface and union fields here.

**Comment by smkhalsa** [comment]
@klavs sure,

The data_builder would generate two constructors for each generated class.

1. The default constructor would take a build function as an argument and would set the `data` property by calling that function. This would be used to manually create an instance of the data class (such as in the optimistic response use case above). 
2. The second constructor would be a named `fromJSON` constructor that would simply set the data property directly.

Using the above example, it might look something like this:

```dart
class $AlbumDetailsQueryBuilder {
  final Map<String, dynamic> data = <String, dynamic>{};

  set Album(
          $AlbumDetailsQuery$AlbumBuilder Function(
                  $AlbumDetailsQuery$AlbumBuilder)
              builder) =>
      data['Album'] = $AlbumDetailsQuery$AlbumBuilder().data;
}

class $AlbumDetailsQuery {
  $AlbumDetailsQuery(
      $AlbumDetailsQueryBuilder Function($AlbumDetailsQueryBuilder) builder)
      : data = builder($AlbumDetailsQueryBuilder()).data;

  const $AlbumDetailsQuery.fromJSON(this.data);

  final Map<String, dynamic> data;

  List<$AlbumDetailsQuery$Album> get Album => data['Album'] == null
      ? null
      : (data['Album'] as List)
          .map((dynamic e) =>
              $AlbumDetailsQuery$Album.fromJSON((e as Map<String, dynamic>)))
          .toList();
}

class $AlbumDetailsQuery$AlbumBuilder {
  final Map<String, dynamic> data = <String, dynamic>{};

  set id(String value) => data['id'] = value;
  set name(String value) => data['name'] = value;
  set imageUrl(String value) => data['imageUrl'] = value;
}

class $AlbumDetailsQuery$Album {
  $AlbumDetailsQuery$Album(
      $AlbumDetailsQuery$AlbumBuilder Function($AlbumDetailsQuery$AlbumBuilder)
          builder)
      : data = builder($AlbumDetailsQuery$AlbumBuilder()).data;

  const $AlbumDetailsQuery$Album.fromJSON(this.data);

  final Map<String, dynamic> data;

  String get id => (data['id'] as String);
  String get name => (data['name'] as String);
  String get imageUrl => (data['imageUrl'] as String);
}

```

As I think more about implementing this, I believe it's worth taking another look at https://github.com/gql-dart/gql/issues/35 since we'd be recreating a lot of the `built_value` functionality (e.g. builder functions, serialization / deserialization).

**Comment by smkhalsa** [comment]
@klavs what do you think about the above change?

As an aside, I'm writing some unit tests and realizing that setters on data_builder would make mocking easier as well.

**Comment by klavs** [comment]
Well... that functionality is missing currently, so we should add it.

I am not convinced about `data_builder` (but mostly because of my lack of practice). I do not want it to hold you back.

Would it make sense to generate interfaces and implementations separately?
