### ISSUE TITLE
generated code doesn't conform to the recommended analysis options

### ISSUE THREAD

**Issue by bahag-raesenerm** [gql-dart/ferry#236]
Hey everyone.
I just want to create this issue for the pure existence, of course it would be nice of `ferry` to conform to linter rules but I guess it's really low priority.

if you setup `analysis_options.yaml` like this:
```yaml
include: package:lints/recommended.yaml
```
([lints](https://pub.dev/packages/lints) is needed as a (dev) dependency)

you'll see thousands of rule conflicts for the generated files. f.e.:
```
Name types using UpperCamelCase.
Name non-constant identifiers using lowerCamelCase.
Annotate overridden members.
Prefer using lowerCamelCase for constant names.
```

as of now you can just ignore this with editing the `analysis_options.yaml`:
```yaml
include: package:lints/recommended.yaml

analyzer:
  exclude: [
    build/**,
    "**/*.schema.gql.dart",
    "**/*.ast.gql.dart",
    "**/*.req.gql.dart",
    "**/*.data.gql.dart",
    "**/*.var.gql.dart",
    "**/*.gql.g.dart",
    "**/*gql.dart"
  ]
```

Greetings

**Comment by smkhalsa** [comment]
Closing this as wontfix since I don't see how we could support it and as you mentioned, there is a simple workaround.

**Comment by bahag-raesenerm** [comment]
you could support it with using the analysis_options yourself - from what I seen it's more or less naming conventions and I guess dart/flutter communities would probably benefit from a common code style.

Anyways, now this issue exists and others can find it and know how things are. Thx for the fast reaction.

**Comment by DeedleFake** [comment]
The workaround is not viable. It completely disables analysis rather than just ignoring rules. This has the rather unfortunate side-effect of completely disabling all VS Code autocompletion support for anything in the excluded files.

The recommended way to support it seems to be to [add an `ignore_for_file` option to the builder](https://github.com/dart-lang/source_gen#configuring-combining_builder-ignore_for_file) that can take a list of ignore rules to insert into the generated file. Then people can just configure it themselves.
