### ISSUE TITLE
After update to 0.3.0:  Undefined name 'ResponseSource'

### ISSUE THREAD

**Issue by Feduch** [gql-dart/ferry#25]
Hi!

Updated ferry yesterday in an error appeared.
When testing on the gql-dart / improve-errors branch, everything was fine.

error: Undefined name 'ResponseSource'. 

![DeepinScreenshot_выберите-область_20200424084204](https://user-images.githubusercontent.com/5888590/80178829-d8e4fc80-8607-11ea-8f5a-a732032ab886.png)

![DeepinScreenshot_выберите-область_20200424085844](https://user-images.githubusercontent.com/5888590/80179879-28c4c300-860a-11ea-9338-ba83540423d5.png)

When I disable internet on phone. 

![DeepinScreenshot_выберите-область_20200424085426](https://user-images.githubusercontent.com/5888590/80179883-29f5f000-860a-11ea-9975-d566c1d47de6.png)
![DeepinScreenshot_выберите-область_20200424085320](https://user-images.githubusercontent.com/5888590/80179884-2a8e8680-860a-11ea-895d-bc75f8ca8452.png)

Maybe I didn’t install the new package correctly?

**Comment by smkhalsa** [comment]
Thanks. Yes, we [decided](https://github.com/gql-dart/ferry/pull/23#discussion_r413921725) to only catch `LinkExceptions`, but it turns out there was an issue with `gql-http-link` not catching IO errors.

Once [this](https://github.com/gql-dart/gql/pull/87) PR is merged it should work correctly. For now, you can reference the PR as your dependency in your pubspec.

**Comment by smkhalsa** [comment]
@Feduch I just realized that the above solution wasn't the solution to the problem you were describing (although you will surely run into the above problem next).

I renamed the type `ResponseSource` to `DataSource` which can now be accessed as  `QueryResponse.dataSource` since in order to fix https://github.com/gql-dart/ferry/issues/16 we will need responses to include data from a cached response but errors from a network response.

Note that per https://github.com/gql-dart/ferry/pull/23#discussion_r413873655 `DataSource.Network` has also been changed to `DataSource.Link`.
