### ISSUE TITLE
Subscription example?

### ISSUE THREAD

**Issue by minhnguyenandpad** [gql-dart/ferry#387]
Does anyone have an example about Subscription. That would be nice.

**Comment by knaeckeKami** [comment]
I agree that this is missing from the documentation. 
Contributions are welcome.

For now, you can check the documentation on the `graphql`package:

https://pub.dev/packages/graphql#subscriptions

https://pub.dev/packages/graphql#basic-usage

https://pub.dev/packages/graphql#links

Basically, you need a WebSocketLink that handles subscriptions, and split up your requests depending on if they are subscriptions or not using `Link.split`.

The API for queries and streams is the same, since both return streams anyway.
