### ISSUE TITLE
[Question] Update cache fragment and queries

### ISSUE THREAD

**Issue by sahmadreza** [gql-dart/ferry#482]
Hi, 

I use the following code to update the post fragment cache after the `update post mutation`,
But when the `update post mutation` is called, the `post list screen` must be refreshed again to update the cache of posts, and the query stream is not updated.

Or better to say it another way, when the `post fragment` cache is updated, I want all queries that have the `post fragment` in the `operation` to be updated as well.

```dart

/// update cache Fragment with the result of executing the UpdatePost Mutation.
UpdateCacheHandler<GUpdatePostData, GUpdatePostVars> postUpdateCacheHandler = (
  proxy,
  response,
) {
  // update Post fragment cache
  final postFragment = GPostReq(
    (b) => b..idFields = {'id': response.data?.post.id},
  );
  final cache = proxy.readFragment(postFragment);
  if (cache != null) {
    proxy.writeFragment(
      postFragment,
      cache.rebuild((b) => b..title =  response.data?.post.title),
    );
  }

};

```

**Post list screen:**
```dart
  final client = GetIt.I<TypedLink>();
  GAllPostReq request = GAllPostReq();

 @override
  void initState() {
    request = request.rebuild((p0) => p0..requestId="homePosts"..vars.first = widget.perPage);
    super.initState();
  }

  /// call when need to refresh list
  Future<void> onRefresh() async {
    request = request.rebuild((p0) => p0..vars.first = widget.perPage);
    setState(() {});
  }

  /// call when need to more items
  Future<void> loadMore(String? cursor, BuiltList<GAllPostData_posts_edges?> items) async {
    if (loadingMore) return;
    final builder = items.toBuilder();

    request = request.rebuild((p0) => p0
      ..vars.after = cursor
      ..updateResult = (previous, result) {
        loadingMore = false;
        builder.addAll(result!.posts.edges ?? []);
        return result.rebuild((b) => b
          ..posts.edges.replace(builder.build())
          ..posts.pageInfo.replace(result.posts.pageInfo));
      });

    setState(() {
      loadingMore = true;
    });
  }


  @override
  Widget build(BuildContext context) {
    return Operation(
      client: client,
      operationRequest: request,
       builder: (BuildContext context, OperationResponse<GAllPostData, GAllPostVars>? response, Object? error) {
         // ... return ListView
      },
     );
  }
```

**Comment by knaeckeKami** [comment]
from this code I cannot see anything wrong. However, there is a lot left out. Do you query the id in your list fragment so the response is normalized correctly? do you actually set the updatecachehandlerkey and is you cachehandler called? ...

**Comment by sahmadreza** [comment]
> Do you query the id in your list fragment so the response is normalized correctly?

Yes, `postUpdateCacheHandler` works correctly and the `post fragment` cache is updated, but the ‍`GAllPostReq‍` query is not updated with the stream at the same time.

The user must refresh the page so that the new data is displayed in the list.

**Comment by knaeckeKami** [comment]
Thanks for the detailed response.

I have some hunch, but take it with a grain of salt; I did take over maintainance of ferry but since I don't use ferry_flutter and have never used this combination of paging + cache updates I might miss something.

To reproduce your basic use case, I added a new test in this PR: 

https://github.com/gql-dart/ferry/pull/483/files

It also uses paging with updateResult, fetches two pages, then edits the cache, which causes the query to emit a third update.

So generally, this seems to work.

What I noticed in your code is that you update the current query and then pass the new query to the operation widget.
I suspect this might cause the RequestControllerTypedLink to lose track of the previous streams and only that last page gets properly watched.

Does it work if you keep passing the original request to your Operation Widget, and handle the paging via the 

`client.requestController.add(newReq)` method?
