### ISSUE TITLE
More detailed documentation.

### ISSUE THREAD

**Issue by mqhamdam** [gql-dart/ferry#536]
Graphql has 3 main operations: Query, Mutation, and Subscription.
Ferry has only one request method which is Stream.
does it mean that all requests are actually streamed and they are never closed automatically after the query fetch is complete?

**Comment by knaeckeKami** [comment]
Can you clarify what you mean by streaming a request and closing it?

**Comment by mqhamdam** [comment]
After generating Schema and other staff, I try to request query mission;
but Ferry Client instance has only one request method and it returns Stream. In normal cases, query should return Future<Response> because it's not a subscription.
# mission schema
```
query Missions() {
    missions() {
      missionState
      id
      description
      startAt
      endAt
      tasks
      priority
      name
    }
  }
  
  query Mission($id: ID!) {
  mission(id: $id) {
    missionState
    id
    description
    startAt
    endAt
    tasks
    priority
    name
  }
}
```
# query mission by id
```
final gMissionReq = GMissionReq((b) => b..vars.id = '1232');
  Client client = Client(link: HttpLink('uri'));

  client.request(gMissionReq).listen((event) {
    print(event.data);
  });
```
# request function from source code
```
@override
  Stream<OperationResponse<TData, TVars>> request<TData, TVars>(
    OperationRequest<TData, TVars> request, [
    forward,
  ]) =>
      _typedLink.request(request, forward);
```
So my question is, do I need to close Stream by myself or it is closed automatically?
And how do I know that GsmthingReq using Query or Subscription?

**Comment by knaeckeKami** [comment]
The stream will be active as long as someone is listening. (e.g. as long as the subscription returned by .listen is not canceled).

When you initially start a request, it will return a response from the network or cache or both (in cache of FetchPolicy.cacheAndNetwork), then keep listening in case:


- the network link returns more data (only relevant for subscriptions)
- the request is refetched / another page is requested using pagination, see https://ferrygraphql.com/docs/pagination
- the cached data of one of the entities included in the response data is updated, either by another request, or by manually writing to the cache, e.g. using cache.writee

This is done to make the help app always show consistent data throughout the UI.
It also means that yes, you have to cancel requests and you don't need them anymore.

If you don't need this. you can call .first instead of .listen, this will only return the first result and not keep listening for updates.

**Comment by mqhamdam** [comment]
Thank you. I got you.

**Comment by yonahforst** [comment]
@knaeckeKami  - what if i have the FetchPolicy set to CacheAndNetwork? I don't want to stop at the first result which might be from the cache, but I do want to close the stream after the network result is returned.
